[build-system]
requires = ["setuptools >= 65.4.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "matplotlib.*",
    "scipy.*",
]
ignore_missing_imports = true